Feature/hamburger menu repair
Dakken-LLC/Dakken-LLC.github.io pull request #19
Opened 2024-12-24 19:29 UTC by IidaKousei

Header完成しました。

2024-12-25 02:20 UTC, okayama-daiki commented on package.json
> +    "react-router-dom": "^7.1.0"
> This package simply re-exports everything from react-router to smooth the upgrade path for v6 applications. Once upgraded you can change all of your imports and remove it from your dependencies:

```diff
-import { Routes } from "react-router-dom"
+import { Routes } from "react-router"
```

https://www.npmjs.com/package/react-router-dom

2024-12-25 03:19 UTC, okayama-daiki requested changes
お疲れ様でした。
何点か修正をお願いします。

2024-12-25 06:04 UTC, IidaKousei commented on src/pages/Home.tsx
> +          target="-blank"
classNameの記法で_はあまり使われないというのを聞いたので＿を-に置換した結果それも間違えて-になってしまったようです.

2024-12-25 06:27 UTC, IidaKousei commented
なおしました

2024-12-26 04:53 UTC, okayama-daiki approved these changes
LGTM です。

![LGTM](https://image.lgtmoon.dev/317570)

2024-12-26 04:57 UTC, merged